version: "2"
services:
   nginx:
     image: prooph/nginx:www
     ports:
         - "80:80"
         - "443:443"
     links:
       - php:php
     volumes_from:
       - php
   php:
     image: prooph/php:7.0-fpm
     links:
       - mariadb:mariadb
     volumes:
         - .:/var/www
   mariadb:
     image: mariadb
     ports:
       - "3307:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=dev
       - MYSQL_USER=dev
       - MYSQL_PASSWORD=dev
       - MYSQL_DATABASE=cargo_sample